<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'slug' => 'company-founded',
                'client' => 'Shabakkat',
                'country' => 'Kuwait',
                'year' => '2005',
                'tag' => 'MILESTONE',
                'color' => 'red',
                'title' => 'Company founded as a regional Engineering & Advisory partner',
                'challenge' => 'The Middle East and Africa needed a single, accountable partner capable of combining engineering execution with project governance and independent advisory.',
                'scope' => ['Engineering & advisory partnership established in Kuwait', 'Foundations set for regional expansion across MEA'],
                'results' => 'Shabakkat is founded, laying the foundation for two decades of critical digital infrastructure delivery.',
                'photo_label' => 'PHOTO — Shabakkat founding milestone, 2005',
                'photo_src' => '/images/projects/founding-milestone.jpg',
                'related_service_href' => '/services/pmo-project-delivery#pmo-project-delivery',
            ],
            [
                'slug' => 'kuwait-managed-services-program',
                'client' => 'STC, Ooredoo & Zain',
                'country' => 'Kuwait',
                'year' => '2009–ongoing',
                'tag' => 'MANAGED SERVICES',
                'color' => 'cyan',
                'title' => 'Managed services program for all three telecom operators',
                'challenge' => "Kuwait's three telecom operators needed a single partner able to run day-to-day network operations, NOC, and field operations at scale.",
                'scope' => ['Day-to-day managed network services for telecom operators', 'Field operations and on-site technical support', '24/7 network operations center (NOC) coverage'],
                'results' => 'A running engagement supporting STC, Ooredoo, and Zain since 2009 with managed services, NOC, and field operations.',
                'photo_label' => 'PHOTO — Kuwait NOC operations',
                'photo_src' => '/images/projects/kuwait-rollout-crew.jpg',
                'related_service_href' => '/services/engineering-services#managed-services',
            ],
            [
                'slug' => 'iraq-nationwide-managed-services',
                'client' => 'Iraq Nationwide',
                'country' => 'Iraq',
                'year' => '2010–ongoing',
                'tag' => 'MANAGED SERVICES',
                'color' => 'cyan',
                'title' => 'Nationwide managed services across Iraq',
                'challenge' => 'Operators in Iraq needed NOC, field maintenance, core operations, and Level 2 support delivered consistently at scale.',
                'scope' => ['Nationwide network operations center (NOC) services', 'Level 2 technical support and escalation handling', 'Core network operations and performance support', 'Field maintenance across active network sites'],
                'results' => 'An ongoing nationwide managed services engagement covering NOC, field maintenance, core operations, and L2 support.',
                'photo_label' => 'PHOTO — Iraq network site',
                'photo_src' => '/images/projects/iraq-network-site.jpg',
                'related_service_href' => '/services/engineering-services#managed-services',
            ],
            [
                'slug' => 'full-turnkey-network-deployment-program',
                'client' => 'Regional Operators',
                'country' => 'Multi-Country',
                'year' => '2012',
                'tag' => 'TURNKEY',
                'color' => 'red',
                'title' => 'Full turnkey network deployment across multiple countries',
                'challenge' => 'Regional operators needed a coordinated turnkey program covering civil works, towers, and site build across several markets simultaneously.',
                'scope' => ['Tower supply, erection, and structural readiness', 'Civil works and site preparation across markets', 'Full turnkey (FTK) network deployment programs', 'End-to-end site build and commissioning'],
                'results' => 'Completed or ongoing by country — a multi-market turnkey deployment program spanning FTK, civil works, towers, and site build.',
                'photo_label' => 'PHOTO — turnkey site build, multi-country',
                'photo_src' => '/images/projects/turnkey-network-deployment.jpg',
                'related_service_href' => '/services/engineering-services#network-rollout',
            ],
            [
                'slug' => 'network-operations-center-expansion',
                'client' => 'Multi-Vendor Operators',
                'country' => 'Regional',
                'year' => '2014',
                'tag' => 'MANAGED SERVICES',
                'color' => 'cyan',
                'title' => 'Expanding multi-vendor NOC operations',
                'challenge' => 'A growing base of managed networks required expanded multi-vendor NOC capacity to maintain service levels.',
                'scope' => ['Continuous monitoring across heterogeneous network environments', 'Fault management and service-level performance support', 'Expanded multi-vendor NOC operations capacity'],
                'results' => 'Network Operations Center capacity expanded to support a growing base of managed multi-vendor networks.',
                'photo_label' => 'PHOTO — multi-vendor NOC expansion',
                'photo_src' => '/images/projects/multi-vendor-noc.jpg',
                'related_service_href' => '/services/engineering-services#managed-services',
            ],
            [
                'slug' => 'radio-benchmark-network-optimization',
                'client' => 'Regional Operators',
                'country' => 'Regional',
                'year' => '2016',
                'tag' => 'RADIO AUDIT',
                'color' => 'red',
                'title' => 'Radio benchmark & network optimization across multiple markets',
                'challenge' => 'Operators needed independent benchmarking and optimization to validate network performance against real customer experience.',
                'scope' => ['Quality of service (QoS) analysis and recommendations', 'Performance optimization across live network layers', 'Independent radio network benchmarking campaigns'],
                'results' => 'Completed benchmarking, optimization, and QoS analysis engagements across multiple regional markets.',
                'photo_label' => 'PHOTO — radio benchmark & drive test data',
                'photo_src' => '/images/projects/radio-benchmark.jpg',
                'related_service_href' => '/services/engineering-services#engineering-technical-services',
            ],
            [
                'slug' => 'consultation-professional-resourcing-program',
                'client' => 'Multiple Clients',
                'country' => 'Regional',
                'year' => '2018–ongoing',
                'tag' => 'CONSULTANCY & RESOURCING',
                'color' => 'navy',
                'title' => 'Consultation & professional resourcing at scale',
                'challenge' => 'Clients across the region needed flexible access to PMO, program management, and engineering resources without building separate in-house teams.',
                'scope' => ['Program management leadership and delivery support', 'Flexible engineering resource deployment at scale', 'Embedded PMO specialists for active programs'],
                'results' => 'An ongoing resourcing program deploying PMO, program management, and engineering resources across active client engagements.',
                'photo_label' => 'PHOTO — engineering team on site',
                'photo_src' => '/images/projects/engineering-team-onsite.jpg',
                'related_service_href' => '/services/pmo-project-delivery#pmo-project-delivery',
            ],
            [
                'slug' => 'iraq-national-field-operations-expansion',
                'client' => 'Iraq',
                'country' => 'Iraq',
                'year' => '2020–ongoing',
                'tag' => 'MANAGED SERVICES',
                'color' => 'cyan',
                'title' => 'Expanding field operations across Iraq',
                'challenge' => 'Large-scale infrastructure required expanded field maintenance, site management, and electrical & mechanical (E&M) support.',
                'scope' => ['Expanded field maintenance across critical infrastructure', 'Electrical & mechanical (E&M) support services', 'On-site management and operational readiness'],
                'results' => 'Field maintenance, site management, and E&M support expanded across Iraq.',
                'photo_label' => 'PHOTO — field operations, Iraq',
                'photo_src' => '/images/projects/iraq-field-operations.jpg',
                'related_service_href' => '/services/engineering-services#managed-services',
            ],
            [
                'slug' => 'pmo-governance-transformation',
                'client' => 'Multiple Clients',
                'country' => 'Regional',
                'year' => '2023–ongoing',
                'tag' => 'PMO',
                'color' => 'navy',
                'title' => 'PMO & governance transformation',
                'challenge' => 'Clients needed stronger project governance, executive reporting, and PMO maturity to manage increasingly complex programs.',
                'scope' => ['Executive reporting and decision-support dashboards', 'PMO maturity uplift across complex programs', 'Project governance frameworks and controls'],
                'results' => 'An ongoing PMO and governance transformation engagement delivering project governance and executive reporting for regional clients.',
                'photo_label' => 'PHOTO — program governance & executive reporting',
                'photo_src' => '/images/projects/pmo-governance.jpg',
                'related_service_href' => '/services/pmo-project-delivery#pmo-project-delivery',
            ],
            [
                'slug' => 'engineering-digital-infrastructure-expansion',
                'client' => 'Multiple Clients',
                'country' => 'Regional',
                'year' => '2025–ongoing',
                'tag' => 'ENGINEERING & ADVISORY',
                'color' => 'red',
                'title' => 'Engineering & digital infrastructure expansion',
                'challenge' => 'Growing regional demand for data centers and digital infrastructure required expanded engineering and advisory capabilities.',
                'scope' => ['Engineering delivery for digital infrastructure programs', 'Data center development and modernization support', 'Technical advisory across planning and execution', 'Critical infrastructure build-out and readiness'],
                'results' => 'Engineering, advisory, data center, and infrastructure capabilities expanded to meet growing regional demand.',
                'photo_label' => 'PHOTO — data center & digital infrastructure expansion',
                'photo_src' => '/images/projects/data-center-expansion.jpg',
                'related_service_href' => '/services/engineering-services#data-centers-digital-infrastructure',
            ],
        ];

        foreach ($projects as $i => $project) {
            Project::updateOrCreate(
                ['slug' => $project['slug']],
                array_merge($project, ['sort_order' => $i]),
            );
        }
    }
}
